// @ts-nocheck
import { default as __fd_glob_52 } from "../../../docs/frameworks/meta.json?collection=docs"
import { default as __fd_glob_51 } from "../../../docs/tooling/meta.json?collection=docs"
import { default as __fd_glob_50 } from "../../../docs/react-native/meta.json?collection=docs"
import { default as __fd_glob_49 } from "../../../docs/animations/meta.json?collection=docs"
import { default as __fd_glob_48 } from "../../../docs/meta.json?collection=docs"
import * as __fd_glob_47 from "../../../docs/animations/variants.mdx?collection=docs"
import * as __fd_glob_46 from "../../../docs/animations/transforms.mdx?collection=docs"
import * as __fd_glob_45 from "../../../docs/animations/svg.mdx?collection=docs"
import * as __fd_glob_44 from "../../../docs/animations/scroll.mdx?collection=docs"
import * as __fd_glob_43 from "../../../docs/animations/scroll-linked.mdx?collection=docs"
import * as __fd_glob_42 from "../../../docs/animations/physics.mdx?collection=docs"
import * as __fd_glob_41 from "../../../docs/animations/layout.mdx?collection=docs"
import * as __fd_glob_40 from "../../../docs/animations/keyframes.mdx?collection=docs"
import * as __fd_glob_39 from "../../../docs/animations/gestures.mdx?collection=docs"
import * as __fd_glob_38 from "../../../docs/animations/filters.mdx?collection=docs"
import * as __fd_glob_37 from "../../../docs/animations/enter-exit.mdx?collection=docs"
import * as __fd_glob_36 from "../../../docs/animations/drag.mdx?collection=docs"
import * as __fd_glob_35 from "../../../docs/animations/basic-properties.mdx?collection=docs"
import * as __fd_glob_34 from "../../../docs/animations/advanced-effects.mdx?collection=docs"
import * as __fd_glob_33 from "../../../docs/tooling/prettier.mdx?collection=docs"
import * as __fd_glob_32 from "../../../docs/tooling/playground.mdx?collection=docs"
import * as __fd_glob_31 from "../../../docs/tooling/migrate.mdx?collection=docs"
import * as __fd_glob_30 from "../../../docs/tooling/mcp.mdx?collection=docs"
import * as __fd_glob_29 from "../../../docs/tooling/eslint.mdx?collection=docs"
import * as __fd_glob_28 from "../../../docs/tooling/cli.mdx?collection=docs"
import * as __fd_glob_27 from "../../../docs/react-native/springs-and-easing.mdx?collection=docs"
import * as __fd_glob_26 from "../../../docs/react-native/scroll-animations.mdx?collection=docs"
import * as __fd_glob_25 from "../../../docs/react-native/llms-txt.mdx?collection=docs"
import * as __fd_glob_24 from "../../../docs/react-native/installation.mdx?collection=docs"
import * as __fd_glob_23 from "../../../docs/react-native/index.mdx?collection=docs"
import * as __fd_glob_22 from "../../../docs/react-native/hooks.mdx?collection=docs"
import * as __fd_glob_21 from "../../../docs/react-native/gestures.mdx?collection=docs"
import * as __fd_glob_20 from "../../../docs/react-native/drag.mdx?collection=docs"
import * as __fd_glob_19 from "../../../docs/react-native/components.mdx?collection=docs"
import * as __fd_glob_18 from "../../../docs/react-native/api-reference.mdx?collection=docs"
import * as __fd_glob_17 from "../../../docs/react-native/animations.mdx?collection=docs"
import * as __fd_glob_16 from "../../../docs/frameworks/vue.mdx?collection=docs"
import * as __fd_glob_15 from "../../../docs/frameworks/vanilla.mdx?collection=docs"
import * as __fd_glob_14 from "../../../docs/frameworks/react.mdx?collection=docs"
import * as __fd_glob_13 from "../../../docs/frameworks/react-native.mdx?collection=docs"
import * as __fd_glob_12 from "../../../docs/frameworks/index.mdx?collection=docs"
import * as __fd_glob_11 from "../../../docs/v2.mdx?collection=docs"
import * as __fd_glob_10 from "../../../docs/syntax.mdx?collection=docs"
import * as __fd_glob_9 from "../../../docs/plan.md?collection=docs"
import * as __fd_glob_8 from "../../../docs/installation.mdx?collection=docs"
import * as __fd_glob_7 from "../../../docs/index.mdx?collection=docs"
import * as __fd_glob_6 from "../../../docs/getting-started.mdx?collection=docs"
import * as __fd_glob_5 from "../../../docs/framework-setup.mdx?collection=docs"
import * as __fd_glob_4 from "../../../docs/extensions.mdx?collection=docs"
import * as __fd_glob_3 from "../../../docs/configuration.mdx?collection=docs"
import * as __fd_glob_2 from "../../../docs/compatibility.mdx?collection=docs"
import * as __fd_glob_1 from "../../../docs/community.mdx?collection=docs"
import * as __fd_glob_0 from "../../../docs/api.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "../../docs", {"meta.json": __fd_glob_48, "animations/meta.json": __fd_glob_49, "react-native/meta.json": __fd_glob_50, "tooling/meta.json": __fd_glob_51, "frameworks/meta.json": __fd_glob_52, }, {"api.mdx": __fd_glob_0, "community.mdx": __fd_glob_1, "compatibility.mdx": __fd_glob_2, "configuration.mdx": __fd_glob_3, "extensions.mdx": __fd_glob_4, "framework-setup.mdx": __fd_glob_5, "getting-started.mdx": __fd_glob_6, "index.mdx": __fd_glob_7, "installation.mdx": __fd_glob_8, "plan.md": __fd_glob_9, "syntax.mdx": __fd_glob_10, "v2.mdx": __fd_glob_11, "frameworks/index.mdx": __fd_glob_12, "frameworks/react-native.mdx": __fd_glob_13, "frameworks/react.mdx": __fd_glob_14, "frameworks/vanilla.mdx": __fd_glob_15, "frameworks/vue.mdx": __fd_glob_16, "react-native/animations.mdx": __fd_glob_17, "react-native/api-reference.mdx": __fd_glob_18, "react-native/components.mdx": __fd_glob_19, "react-native/drag.mdx": __fd_glob_20, "react-native/gestures.mdx": __fd_glob_21, "react-native/hooks.mdx": __fd_glob_22, "react-native/index.mdx": __fd_glob_23, "react-native/installation.mdx": __fd_glob_24, "react-native/llms-txt.mdx": __fd_glob_25, "react-native/scroll-animations.mdx": __fd_glob_26, "react-native/springs-and-easing.mdx": __fd_glob_27, "tooling/cli.mdx": __fd_glob_28, "tooling/eslint.mdx": __fd_glob_29, "tooling/mcp.mdx": __fd_glob_30, "tooling/migrate.mdx": __fd_glob_31, "tooling/playground.mdx": __fd_glob_32, "tooling/prettier.mdx": __fd_glob_33, "animations/advanced-effects.mdx": __fd_glob_34, "animations/basic-properties.mdx": __fd_glob_35, "animations/drag.mdx": __fd_glob_36, "animations/enter-exit.mdx": __fd_glob_37, "animations/filters.mdx": __fd_glob_38, "animations/gestures.mdx": __fd_glob_39, "animations/keyframes.mdx": __fd_glob_40, "animations/layout.mdx": __fd_glob_41, "animations/physics.mdx": __fd_glob_42, "animations/scroll-linked.mdx": __fd_glob_43, "animations/scroll.mdx": __fd_glob_44, "animations/svg.mdx": __fd_glob_45, "animations/transforms.mdx": __fd_glob_46, "animations/variants.mdx": __fd_glob_47, });