// @ts-nocheck
import * as __fd_glob_52 from "../../../docs/tooling/prettier.mdx?collection=docs"
import * as __fd_glob_51 from "../../../docs/tooling/playground.mdx?collection=docs"
import * as __fd_glob_50 from "../../../docs/tooling/migrate.mdx?collection=docs"
import * as __fd_glob_49 from "../../../docs/tooling/mcp.mdx?collection=docs"
import * as __fd_glob_48 from "../../../docs/tooling/eslint.mdx?collection=docs"
import * as __fd_glob_47 from "../../../docs/tooling/cli.mdx?collection=docs"
import * as __fd_glob_46 from "../../../docs/react-native/springs-and-easing.mdx?collection=docs"
import * as __fd_glob_45 from "../../../docs/react-native/scroll-animations.mdx?collection=docs"
import * as __fd_glob_44 from "../../../docs/react-native/llms-txt.mdx?collection=docs"
import * as __fd_glob_43 from "../../../docs/react-native/installation.mdx?collection=docs"
import * as __fd_glob_42 from "../../../docs/react-native/index.mdx?collection=docs"
import * as __fd_glob_41 from "../../../docs/react-native/hooks.mdx?collection=docs"
import * as __fd_glob_40 from "../../../docs/react-native/gestures.mdx?collection=docs"
import * as __fd_glob_39 from "../../../docs/react-native/drag.mdx?collection=docs"
import * as __fd_glob_38 from "../../../docs/react-native/components.mdx?collection=docs"
import * as __fd_glob_37 from "../../../docs/react-native/api-reference.mdx?collection=docs"
import * as __fd_glob_36 from "../../../docs/react-native/animations.mdx?collection=docs"
import * as __fd_glob_35 from "../../../docs/frameworks/vue.mdx?collection=docs"
import * as __fd_glob_34 from "../../../docs/frameworks/vanilla.mdx?collection=docs"
import * as __fd_glob_33 from "../../../docs/frameworks/react.mdx?collection=docs"
import * as __fd_glob_32 from "../../../docs/frameworks/react-native.mdx?collection=docs"
import * as __fd_glob_31 from "../../../docs/frameworks/index.mdx?collection=docs"
import * as __fd_glob_30 from "../../../docs/animations/variants.mdx?collection=docs"
import * as __fd_glob_29 from "../../../docs/animations/transforms.mdx?collection=docs"
import * as __fd_glob_28 from "../../../docs/animations/svg.mdx?collection=docs"
import * as __fd_glob_27 from "../../../docs/animations/scroll.mdx?collection=docs"
import * as __fd_glob_26 from "../../../docs/animations/scroll-linked.mdx?collection=docs"
import * as __fd_glob_25 from "../../../docs/animations/physics.mdx?collection=docs"
import * as __fd_glob_24 from "../../../docs/animations/layout.mdx?collection=docs"
import * as __fd_glob_23 from "../../../docs/animations/keyframes.mdx?collection=docs"
import * as __fd_glob_22 from "../../../docs/animations/gestures.mdx?collection=docs"
import * as __fd_glob_21 from "../../../docs/animations/filters.mdx?collection=docs"
import * as __fd_glob_20 from "../../../docs/animations/enter-exit.mdx?collection=docs"
import * as __fd_glob_19 from "../../../docs/animations/drag.mdx?collection=docs"
import * as __fd_glob_18 from "../../../docs/animations/basic-properties.mdx?collection=docs"
import * as __fd_glob_17 from "../../../docs/animations/advanced-effects.mdx?collection=docs"
import * as __fd_glob_16 from "../../../docs/v2.mdx?collection=docs"
import * as __fd_glob_15 from "../../../docs/syntax.mdx?collection=docs"
import * as __fd_glob_14 from "../../../docs/plan.md?collection=docs"
import * as __fd_glob_13 from "../../../docs/installation.mdx?collection=docs"
import * as __fd_glob_12 from "../../../docs/index.mdx?collection=docs"
import * as __fd_glob_11 from "../../../docs/getting-started.mdx?collection=docs"
import * as __fd_glob_10 from "../../../docs/framework-setup.mdx?collection=docs"
import * as __fd_glob_9 from "../../../docs/extensions.mdx?collection=docs"
import * as __fd_glob_8 from "../../../docs/configuration.mdx?collection=docs"
import * as __fd_glob_7 from "../../../docs/compatibility.mdx?collection=docs"
import * as __fd_glob_6 from "../../../docs/community.mdx?collection=docs"
import * as __fd_glob_5 from "../../../docs/api.mdx?collection=docs"
import { default as __fd_glob_4 } from "../../../docs/tooling/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../../../docs/react-native/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../../../docs/frameworks/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../../../docs/animations/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../../../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "../../docs", {"meta.json": __fd_glob_0, "animations/meta.json": __fd_glob_1, "frameworks/meta.json": __fd_glob_2, "react-native/meta.json": __fd_glob_3, "tooling/meta.json": __fd_glob_4, }, {"api.mdx": __fd_glob_5, "community.mdx": __fd_glob_6, "compatibility.mdx": __fd_glob_7, "configuration.mdx": __fd_glob_8, "extensions.mdx": __fd_glob_9, "framework-setup.mdx": __fd_glob_10, "getting-started.mdx": __fd_glob_11, "index.mdx": __fd_glob_12, "installation.mdx": __fd_glob_13, "plan.md": __fd_glob_14, "syntax.mdx": __fd_glob_15, "v2.mdx": __fd_glob_16, "animations/advanced-effects.mdx": __fd_glob_17, "animations/basic-properties.mdx": __fd_glob_18, "animations/drag.mdx": __fd_glob_19, "animations/enter-exit.mdx": __fd_glob_20, "animations/filters.mdx": __fd_glob_21, "animations/gestures.mdx": __fd_glob_22, "animations/keyframes.mdx": __fd_glob_23, "animations/layout.mdx": __fd_glob_24, "animations/physics.mdx": __fd_glob_25, "animations/scroll-linked.mdx": __fd_glob_26, "animations/scroll.mdx": __fd_glob_27, "animations/svg.mdx": __fd_glob_28, "animations/transforms.mdx": __fd_glob_29, "animations/variants.mdx": __fd_glob_30, "frameworks/index.mdx": __fd_glob_31, "frameworks/react-native.mdx": __fd_glob_32, "frameworks/react.mdx": __fd_glob_33, "frameworks/vanilla.mdx": __fd_glob_34, "frameworks/vue.mdx": __fd_glob_35, "react-native/animations.mdx": __fd_glob_36, "react-native/api-reference.mdx": __fd_glob_37, "react-native/components.mdx": __fd_glob_38, "react-native/drag.mdx": __fd_glob_39, "react-native/gestures.mdx": __fd_glob_40, "react-native/hooks.mdx": __fd_glob_41, "react-native/index.mdx": __fd_glob_42, "react-native/installation.mdx": __fd_glob_43, "react-native/llms-txt.mdx": __fd_glob_44, "react-native/scroll-animations.mdx": __fd_glob_45, "react-native/springs-and-easing.mdx": __fd_glob_46, "tooling/cli.mdx": __fd_glob_47, "tooling/eslint.mdx": __fd_glob_48, "tooling/mcp.mdx": __fd_glob_49, "tooling/migrate.mdx": __fd_glob_50, "tooling/playground.mdx": __fd_glob_51, "tooling/prettier.mdx": __fd_glob_52, });